// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository_Layer.DatabaseContexts;

namespace ChatApi.Migrations
{
    [DbContext(typeof(ChatContext))]
    [Migration("20180713124812_RemovedMessageIdFromUser")]
    partial class RemovedMessageIdFromUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Repository_Layer.DtoModels.MessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .HasMaxLength(125);

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("ReceivedDate");

                    b.Property<Guid?>("SenderId");

                    b.Property<DateTime>("SentDate");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("Repository_Layer.DtoModels.MessageRecipientEntity", b =>
                {
                    b.Property<Guid>("MessageId");

                    b.Property<Guid?>("RecipientId");

                    b.HasKey("MessageId", "RecipientId");

                    b.HasIndex("RecipientId");

                    b.ToTable("MessageRecipient");
                });

            modelBuilder.Entity("Repository_Layer.DtoModels.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25);

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Repository_Layer.DtoModels.MessageEntity", b =>
                {
                    b.HasOne("Repository_Layer.DtoModels.UserEntity", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");
                });

            modelBuilder.Entity("Repository_Layer.DtoModels.MessageRecipientEntity", b =>
                {
                    b.HasOne("Repository_Layer.DtoModels.MessageEntity", "Messages")
                        .WithMany("MessageRecipient")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Repository_Layer.DtoModels.UserEntity", "Users")
                        .WithMany("MessageRecipient")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
